site_name: Umm
extra_css:
  - assets/styles.css
theme:
    name: material
    custom_dir: overrides
    palette:
        scheme: default # default, slate
        primary: white # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey, black, white
        accent: amber
    font:
      text: Open Sans
      code: Roboto Mono
    logo: assets/logo1.png
    favicon: assets/logo1.png
    features:
    - navigation.tracking #updates url with new paths
    - content.tooltips
    - navigation.tabs
    icon:
      admonition:
        note: fontawesome/solid/vial
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: fontawesome/solid/vial
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - About: about.md
  - Newsletter: https://buttondown.email/umm/
  - Docs (outdated): https://github.com/universal-meaning-map/docs