site_name: Umm
extra_css:
  - assets/styles.css
theme:
    name: material
    palette:
        scheme: default # default, slate
        primary: white # red, pink, purple, deep purple, indigo, blue, light blue, cyan, teal, green, light green, lime, yellow, amber, orange, deep orange, brown, grey, blue grey, black, white
        accent: amber
    font:
      text: Open Sans
      code: Roboto Mono
    logo: assets/logo1.png
    favicon: assets/logo1.png
    features:
    - navigation.instant.preview
    - navigation.instant
    - navigation.tracking #updates url with new paths
    - content.tooltips
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets

nav:
  - Framework:
    - What something is: framework/what-does-it-mean-that-something-is.md
    - An intro to Umm: framework/intro-to-umm.md
    - Nested:
      - Item1: nothing
      - Item 3: nothing
      - Nested:
        - Item 4: something
        - Item5: something
  - Terminology: terminology.md